### ISSUE TITLE
Property 'ɵunwrapWritableSignal' does not exist on type

### ISSUE THREAD

**Issue by albancho** [angular/vscode-ng-language-service#2001]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 17.1.1

### Description

Since updating to version 17.2.0,
`Property 'ɵunwrapWritableSignal' does not exist on type xxx/node_modules/@angular/core/index` shows up on [(ngModel)]

**Comment by arnotixe** [comment]
extension 
Just searched through my code, and it squiggles all 132 occurances of `[(ngModel)]` no matter the component type
![image](https://github.com/angular/vscode-ng-language-service/assets/500938/5c40fb42-ccbe-461e-a024-be1b06bf3638)



And also squiggles the prop in my home grown components using that **same kind of bi-directional binding**:
![image](https://github.com/angular/vscode-ng-language-service/assets/500938/ade127a5-7d24-45db-9c6a-35a23e4f5c9c)
```
export class LoginselectorComponent implements OnInit {
  @Input() altselect = false;
  @Output() altselectChange = new EventEmitter<boolean>();
  …
```

app still builds and deploys though :partying_face: so I guess it's an editor nuisance only

**Comment by gcoadour** [comment]
> Please check that your angular language service has been updateed. The latest release (2/12/2024) fixes this.

it's version 17.2.0 that adds the problem, if you go back to version 17.1.1 then it's not there. 
You can see here that several users are affected: https://stackoverflow.com/questions/77986204/property-%c9%b5unwrapwritablesignal-does-not-exist-on-type/77987961#77987961

**Comment by JeanMeche** [comment]
Yes my bad, it was the other way around.

**Comment by AndrewKushnir** [comment]
Thanks for reporting the issue. The problem is that a newer version of Angular compiler (used within the Language Service) relied on some symbols that were added in an RC version of 17.2.0.

We'll work on improving version detection to prevent such issues in the future. Meanwhile we plan to rollback a version change in the Language Service and publish it as 17.2.1 shortly.

**Comment by husnainkhan620** [comment]
I am seeing the same with version 16.2.10  'Property 'ɵunwrapWritableSignal' does not exist on type 'typeof '

**Comment by AndrewKushnir** [comment]
Quick update: Language Service VSCode extension with a previous version of the compiler is now released as v17.2.1 ([release info](https://github.com/angular/vscode-ng-language-service/releases/tag/v17.2.1)). Note: it may take a couple hours for a new version to become available for download at the marketplace.

I'm closing this ticket as completed for now, please reopen if the problem still exists after updating to v17.2.1.

**Comment by andreidiaconescu** [comment]
Hello,

Issue reproduces after updating to Angular Language Service 17.2.2.
At version 17.2.1 the issue was not reproducing.

**Comment by max-mohr** [comment]
Hello,

I can also confirm that the issue is still there for v17.2.2.
I skipped v17.2.1 because I had already downgraded to v17.1.1 so I cannot say that 17.2.1 would have fixed the issue for me.

But still v17.2.2 has the problem

**Comment by alxhub** [comment]
If you're able to create a self-contained repro and share it (likely as a Github repo) that would be incredibly helpful in tracking down this issue. Also, uploading your language service log (Command Palette > Angular: Open Angular Server log) would also help (please check if it contains data you don't want to share - all we really need is any line that mentions `_angularCoreVersion`).

**Comment by alxhub** [comment]
(reopening for visibility, until we can confirm that the problem is indeed fixed)

**Comment by felikshetalia** [comment]
i have this problem in 17.1 though, i tried downgrading but the problem was still there.

**Comment by jonasduever** [comment]
Still have this issue on v17.2.2.

Downgrading to v17.1.1 "solved" it for now.

(`@angular/core: 17.0.4` - will try if upgrading the `@angular/*` dependencies solves it later this week.)

**Comment by jpike88** [comment]
Fixed by just updating angular to latest version (in case it's not obvious to some)

**Comment by OnurEAkgul** [comment]
I have the issue on v17.2.2 Its still happening on ngModels

**Comment by atscott** [comment]
Could someone who is still experiencing this issue please provide a reproduction? 

This has not been reproducible since 17.2.2 and will be closed soon without the ability to confirm it's an issue with the extension rather than a setup issue (failing to reload VSCode, having multiple versions of Angular in node modules, etc).

**Comment by andreidiaconescu** [comment]
Hello,
as mentioned in a previous comment, for me,  this issue does reproduce on the latest version:
17.2.2 but not on version 17.2.1
in some of the templates where i have
 [(ngModel)]="eventEndDate"
for example:
```
            <input
              matInput
              [matDatepicker]="eventDownloadStartDate"
              [max]="maxDateValidation"
              name="eventStartDate"
              [(ngModel)]="eventStartDate"
            />
```
the error is
```
Property 'ɵunwrapWritableSignal' does not exist on type 'typeof import("/mnt/otherLinuxPartition/var/www/kickstart/frontend/node_modules/@angular/core/index")'.ngtsc(2339)
general-settings.component.ts(14, 45): Error occurs in the template of component GeneralSettingsComponent.
public (property) GeneralSettingsComponent.eventStartDate: Date
```

**Comment by dopsun** [comment]
Thanks @atscott 

Today I upgraded the Angular version for two of my projects. Issue disappeared after running following:
```
ng update @angular/core@17 @angular/cli@17
```
This brings my Angular version to `17.2.2`. I have tested with two existing projects separately, both work after upgrade.

And I also cannot reproduce issue starting form scratch.

**Comment by dopsun** [comment]
Another coincident finding is that. For my 2nd project, I upgrade with `ng update`, and then git rollback `package.json` and `package-lock.json` files only, it still works without any issue.

Not sure this adds any extra value, but happy to share here.

**Comment by janaka** [comment]
FYI seeing this issue with Angular 14 + extension v17.2.2. v17.1.1 seems to resolve as suggested. 👍🏾

**Comment by alxhub** [comment]
> If you're able to create a self-contained repro and share it (likely as a Github repo) that would be incredibly helpful in tracking down this issue. Also, uploading your language service log (Command Palette > Angular: Open Angular Server log) would also help (please check if it contains data you don't want to share - all we really need is any line that mentions `_angularCoreVersion`).

(asking again for reproduction/logs which would be super helpful in tracking down these issues)

**Comment by atscott** [comment]
@janaka @Licen-it I was also not able to reproduce this issue in 14.0.0 or 14.2.0. We've mentioned a few times that we will need a project that the issue can be reproduced with, as we haven't been able to with any of the listed versions in previous comments.

**Comment by Licen-it** [comment]
> @janaka @Licen-it I was also not able to reproduce this issue in 14.0.0 or 14.2.0. We've mentioned a few times that we will need a project that the issue can be reproduced with, as we haven't been able to with any of the listed versions in previous comments.

I tried to setup a new mini-project using one of the examples in the angular tutorial, but I wasn't able to reproduce it, so unless it's involving some other dependencies i have in the project, the only difference between the 2 was that with the project where i can reproduce the issue i use yarn, while in the other i used npm. I don't think this difference would impact the angular extension in any way, but worth to share anyway.
I'll try to see if i can get logs as @alxhub mentioned

**Comment by janaka** [comment]
> @janaka @Licen-it I was also not able to reproduce this issue in 14.0.0 or 14.2.0. We've mentioned a few times that we will need a project that the issue can be reproduced with, as we haven't been able to with any of the listed versions in previous comments.

I forgot to mention this VS Code on windows.

The project is private unfortunately.

**Comment by Cronkan** [comment]
@atscott 
Here is a repo where i've reproduced it: https://github.com/Cronkan/language-server-error
Seems to be version specific, we run 17.1.2 atm in our projects, generating a new projects with ^17.2.3 does not seem to have the same problem.

**Comment by alxhub** [comment]
> I tried to setup a new mini-project using one of the examples in the angular tutorial, but I wasn't able to reproduce it, so unless it's involving some other dependencies i have in the project, the only difference between the 2 was that with the project where i can reproduce the issue i use yarn, while in the other i used npm. I don't think this difference would impact the angular extension in any way, but worth to share anyway. I'll try to see if i can get logs as @alxhub mentioned

Thanks, that would be very helpful!

**Comment by atscott** [comment]
@Cronkan Hmm, I was not seeing the issue in your reproduction either. Some more information would be helpful. Here are some things to look at:

Looking at the output channel and the angular server logs ("Angular: open Angular server log" in command palette), the extension should have identified that you're using 17.1.2:
<img width="1295" alt="Screenshot 2024-02-29 at 9 37 41 AM" src="https://github.com/angular/vscode-ng-language-service/assets/479713/5944cb33-9265-4293-93a7-0ef3c05ae521">

Viewing the type check block of the component did not show an attempted use of the `ɵunwrapWritableSignal` function:
<img width="1336" alt="Screenshot 2024-02-29 at 9 41 59 AM" src="https://github.com/angular/vscode-ng-language-service/assets/479713/e3280dde-01db-4a5a-b39d-9649697d9814">

When I updated the version to 17.2.2, the version is again identified correctly
<img width="1373" alt="Screenshot 2024-02-29 at 9 43 39 AM" src="https://github.com/angular/vscode-ng-language-service/assets/479713/1cd442c8-e897-4f8a-865a-eefe68ad4520">
<img width="991" alt="Screenshot 2024-02-29 at 9 38 40 AM" src="https://github.com/angular/vscode-ng-language-service/assets/479713/56a0c32f-5416-4dd1-94ab-1edf34641975">

**Comment by frozenfrank** [comment]
I was experiencing this issue on Angular Language Service `v17.2.2`, but then after reading this whole thread, I restarted VScode and the issue stopped happening. It's resolved for me now!

<img width="308" alt="image" src="https://github.com/angular/vscode-ng-language-service/assets/19808440/829ad0a1-d34b-4a72-ab20-4634773ee238">

**Comment by Cronkan** [comment]
@atscott 
Yeah sorry, seems like it used the wrong angular version after i downgraded in package.json. Restarting the language-server made it work. :(
Thing is that the `Using Angular version xx.x.x` doesn't show at the top in the projects that has the error (the one i provided works): 
![image](https://github.com/angular/vscode-ng-language-service/assets/6704780/f89916fb-e5f7-4eab-86c2-29e497eee91c)

I compared the `tsconfig.ts` etc. and `angular.json` and changed some stuff that wasn't the same but no dice.
Also turned on logging and server messages and looks the same. So the culprit seems to be `Using Angular version xx.x.x` but that doesn't show up in the logs.

Update: I found that when i open the web project directly i dont get the error. But when opening the project folder containing multiple projects in the structure like:
```
./src/Project.Web
./src/Project.WebAPI
```
I get the error.
Here is a new repo for the error: https://github.com/Cronkan/language-server-error-folder
Open the root so you can see `\src\lang-error\src` etc.

**Comment by atscott** [comment]
> Update: I found that when i open the web project directly i dont get the error. But when opening the project folder containing multiple projects in the structure like:

@Cronkan Okay, yes that would be the issue. The extension is not able to find nested `node_modules` folders when trying to determine the project versions at startup. In addition, this determination is made once on startup and uses the same options for all projects in the workspace.

As a temporary workaround, you can add your angular project folder to the workspace so it is one of the workspace roots. Using your reproduction, here the extension identifies the version correctly:

![Screenshot 2024-02-29 at 12 27 58 PM](https://github.com/angular/vscode-ng-language-service/assets/479713/a392eb48-88df-4bbe-ba85-944ade52836c)
![Screenshot 2024-02-29 at 12 28 16 PM](https://github.com/angular/vscode-ng-language-service/assets/479713/980a1101-4ba2-43c2-a4e8-fa7e29ef0057)

**Comment by Licen-it** [comment]
> > Update: I found that when i open the web project directly i dont get the error. But when opening the project folder containing multiple projects in the structure like:
> 
> @Cronkan Okay, yes that would be the issue. The extension is not able to find nested `node_modules` folders when trying to determine the project versions at startup. In addition, this determination is made once on startup and uses the same options for all projects in the workspace.
> 
> As a temporary workaround, you can add your angular project folder to the workspace so it is one of the workspace roots. Using your reproduction, here the extension identifies the version correctly:
> 
> ![Screenshot 2024-02-29 at 12 27 58 PM](https://private-user-images.githubusercontent.com/479713/309065221-a392eb48-88df-4bbe-ba85-944ade52836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNDAzOTIsIm5iZiI6MTcwOTI0MDA5MiwicGF0aCI6Ii80Nzk3MTMvMzA5MDY1MjIxLWEzOTJlYjQ4LTg4ZGYtNGJiZS1iYTg1LTk0NGFkZTUyODM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQyMDU0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzg3MmMxMWU5MjIyMzQwZTc3NjY0M2I1MDBjNmY2NmRjMTZjNTFhZGYyMGFlOTc3MzA0NTM3YmYyNjkwY2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WdaHQMWDqufx-B4UsgvA5FfLimJJ4iuZBuJuI_Br8pU) ![Screenshot 2024-02-29 at 12 28 16 PM](https://private-user-images.githubusercontent.com/479713/309065228-980a1101-4ba2-43c2-a4e8-fa7e29ef0057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNDAzOTIsIm5iZiI6MTcwOTI0MDA5MiwicGF0aCI6Ii80Nzk3MTMvMzA5MDY1MjI4LTk4MGExMTAxLTRiYTItNDNjMi1hNGU4LWZhN2UyOWVmMDA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQyMDU0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWNlMjQ5MGZlNmY0NmU1OTVjOGM2ZGQ2Mjg0ZTk0Yzg4OGRmZGRhZmM3MGUyMTlkNDQ0YjdhMDVkYjZiZDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LLW59LDD8nG-qLhT_LVZrV094sHzbWSdTf2b4LbpLUM)

Ok then that would explain why i wasn't able to reproduce with the example project i tried, but i can in my work project.
In my project structure the root level is not the angular project for the UI...that is inside a nested folder. I configured vscode angular service to point at the angular.json level instead looking for angular at the top folder.
My structure is something like:
```
Root
    |-- backend folder
    |-- ui folder
              |-- node_modules
```

**Comment by Cronkan** [comment]
> > Update: I found that when i open the web project directly i dont get the error. But when opening the project folder containing multiple projects in the structure like:
> 
> @Cronkan Okay, yes that would be the issue. The extension is not able to find nested `node_modules` folders when trying to determine the project versions at startup. In addition, this determination is made once on startup and uses the same options for all projects in the workspace.
> 
> As a temporary workaround, you can add your angular project folder to the workspace so it is one of the workspace roots. Using your reproduction, here the extension identifies the version correctly:
> 
> ![Screenshot 2024-02-29 at 12 27 58 PM](https://private-user-images.githubusercontent.com/479713/309065221-a392eb48-88df-4bbe-ba85-944ade52836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTY0NTQsIm5iZiI6MTcwOTI5NjE1NCwicGF0aCI6Ii80Nzk3MTMvMzA5MDY1MjIxLWEzOTJlYjQ4LTg4ZGYtNGJiZS1iYTg1LTk0NGFkZTUyODM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmU5NWExYmFjMGI3NWNmY2VkYmE4N2FiZDU1NmE3OWEyNWRmMmNkNGJmYmQ5YTkwMTdkNWUxMjlhMjM4NTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TZ_xwNvswARNsPd2LbBEISWzpSMvnlqWtOYKAXSRTQM) ![Screenshot 2024-02-29 at 12 28 16 PM](https://private-user-images.githubusercontent.com/479713/309065228-980a1101-4ba2-43c2-a4e8-fa7e29ef0057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTY0NTQsIm5iZiI6MTcwOTI5NjE1NCwicGF0aCI6Ii80Nzk3MTMvMzA5MDY1MjI4LTk4MGExMTAxLTRiYTItNDNjMi1hNGU4LWZhN2UyOWVmMDA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjI5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzRlYmNlYzNhMTdhMzE3YTkwNjg4YTk5MDVjZWQ2M2IzMzExNDU1NDg1NGUzOTc2OWJlYjg0MDk2ODY4ZDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R1ZEwCFR-A5-tU87oxmMGGdBofRcTkDSHX2-wB-C7_8)

Great!
The issue seems also only affect banana-in-the-box `[(var)]` which had no problems in previous versions.
If it's hard to fix, could an alternative be to provide a setting for overriding `angularCoreVersion` that we can place in our `./.vscode/settings.json` for the time beeing? i.e `"angular.coreVersion": "17.1.2"`

**Comment by Licen-it** [comment]
> > Is it something fixable in the extension?
> 
> Yes. I can't commit to a timeframe but this should absolutely be fixable in the extension and we will be investigating what can be done here.

oh also could you consider as well the following folder structure when fixing the issue?

```
root
  |-- ui folder 1
  |        |-- node_modules
  |-- ui folder 2
  |        |-- node_modules
  |-- backend folder
```
where the two UI folders would have different package.json and angular configuration? In my use case they have same angular version so no big deal, but i believe a solution where you can in case set which one would be the main folder to setup the angular version for the project would be a nice to have

**Comment by atscott** [comment]
This should be fixed in the 17.3.1 release
